language: python
python:
    - "2.7"
notifications:
    email: comses-dev@googlegroups.com
env: DB=postgres
services:
    - memcached
    - redis
before_script:
    - curl -sSL https://raw.githubusercontent.com/tgpatel/travis-solr/add_support_for_5.0.0/travis-solr.sh | SOLR_VERSION=5.0.0 bash
    - cp catalog/settings/local.py.example catalog/settings/local.py
    - fab setup
install: "pip install -r requirements.txt"
script: fab coverage
after_success:
    - coveralls
