language: "python"
sudo: required
python:
  - "3.5"
notifications:
  email: comses-dev@googlegroups.com
services:
  - docker
env: 
  DOCKER_COMPOSE_VERSION: 1.15.0
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y docker-ce
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - ln -s development.yml docker-compose.yml 
  - docker-compose version
install: 
  - pip install python-coveralls coverage
  - docker-compose build --pull
script:
  - docker-compose run --rm django /code/deploy/docker/test.sh
after_success:
  - mv .coverage{,.123} && coverage combine --append && coveralls
