language: "python"
sudo: required
python:
  - "3.6"
notifications:
  email: comses-dev@googlegroups.com
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
env: 
  DOCKER_COMPOSE_VERSION: 1.24.0
before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - ./compose
  - ./deploy.sh tag
  - sudo sysctl -w vm.max_map_count=262144
install: 
  - docker --version
  - ./build.sh
  - pip3 install python-coveralls coverage
script:
  - docker-compose run --rm django /code/deploy/docker/test.sh
after_success:
  - mv .coverage{,.123} && coverage combine --append && coveralls
