language: python
python:
    - "2.7"
notifications:
    email: comses-dev@googlegroups.com
env: DB=postgres
services:
    - memcached
    - redis
before_script:
    - sudo apt-get -y install solr-tomcat
    - cp catalog/settings/local.py.example catalog/settings/local.py
    - fab setup_postgres
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py build_solr_schema > ./schema.xml
    - sudo cp ./schema.xml /etc/solr/conf/schema.xml
    - service tomcat6 restart
    - python manage.py rebuild_index
install: "pip install -r requirements.txt"
script: fab coverage
after_success:
    - coveralls
