language: python
sudo: false
python:
    - "3.5"
notifications:
    email: comses-dev@googlegroups.com
env: 
    - DB=postgres SOLR_VERSION=4.10.4 SOLR_CORE=catalog SOLR_CONFS="schema.xml deploy/travis/solrconfig.xml"
services:
    - redis
before_script:
    - ./manage.py build_solr_schema > schema.xml
    - bash deploy/travis/travis-solr.sh # edited from https://github.com/moliware/travis-solr
    - cp catalog/settings/local.py.example catalog/settings/local.py
    - invoke setup_postgres
    - invoke initialize_database_schema
    - curl http://localhost:8983/solr/admin/cores?action=RELOAD&core=catalog
    - yes | invoke rebuild_index
install: "pip install -r requirements.txt"
script: invoke coverage
after_success:
    - coveralls
after_failure:
    - ls solr-${SOLR_VERSION}/example/multicore/catalog/conf
    - ls solr-${SOLR_VERSION}/example/solr/collection1/conf
