version: '2'
services:
## look into https://github.com/nazariyg/Solr-5-for-django-haystack
  solr:
    image: comses/solr
    ports:
      - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - catalog_core
  db:
    image: postgres:9
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: catalog
      # FIXME: replace with env_file (https://docs.docker.com/v1.8/compose/yml/#env-file)
      POSTGRES_PASSWORD: CHANGEME_CATALOG_DB_PASSWORD
      POSTGRES_DB: comses_catalog
  django:
    build:
      context: ./
    volumes:
      - .:/code
      - solr:/etc/solr/mycores/
      - logs:/catalog/logs
    entrypoint: 
      - /code/deploy/docker/dev.sh
    environment:
      DB_USER: catalog
      DB_HOST: db
      DB_NAME: comses_catalog
      DB_PORT: 5432
      SOLR_HOST: solr
      SOLR_PORT: 8983
      SOLR_CORE_NAME: catalog_core
    ports:
      - "8000:8000"
    links:
      - db
      - solr
  test:
    build:
      context: ./
    volumes:
      - .:/code
      - solr:/etc/solr/mycores/
      - logs:/catalog/logs
    entrypoint: 
      - /code/deploy/docker/test.sh 
    environment:
      DB_USER: catalog
      DB_HOST: db
      DB_NAME: comses_catalog
      DB_PORT: 5432
      SOLR_HOST: solr
      SOLR_PORT: 8983
      SOLR_CORE_NAME: catalog_core
    links:
      - db
      - solr
volumes:
  solr:
    driver: local
  data:
    driver: local
  static:
    driver: local
  logs:
    driver: local
