version: '3.3'

services:
  db:
    secrets:
      - catalog_db_password
  elasticsearch:
    environment:
      - network.host=_eth0:ipv4_
      - discovery.type=zen
      - discovery.zen.ping.unicast.hosts=tasks.elasticsearch
  django:
    build:
      args:
        RUN_SCRIPT: "./deploy/docker/prod.sh"
      context: ./
      dockerfile: ./deploy/images/django.Dockerfile
    image: comses/catalog/prod:latest
    expose:
      - "5006"
    restart: always
    secrets:
      - catalog_django_config
    volumes:
      - ./deploy/backup/cron-script:/etc/cron.daily/autopgsqlbackup
      - static:/catalog/static
      - uwsgisocket:/catalog/socket
  nginx:
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: uwsgi_params
        target: /catalog/uwsgi_params
    image: nginx:latest
    restart: always
    volumes:
    - uwsgisocket:/catalog/socket
    - static:/catalog/static
    - logs:/var/log/nginx
    command: ["nginx", "-g", "daemon off;"]
    deploy:
      mode: global
    ports:
      - "80:80"
    depends_on:
      - django
  solr:
    configs:
      - source: solr_in_sh
        target: /opt/solr/bin/solr.in.sh

configs:
  nginx_conf:
    file: ./deploy/nginx/catalog-haproxy.conf
  solr_in_sh:
    file: ./deploy/solr/init.d/solr.in.sh
  uwsgi_params:
    file: ./deploy/nginx/uwsgi_params

volumes:
  uwsgisocket:
    driver: local

secrets:
  catalog_django_config:
    file: ./deploy/conf/config.ini
  catalog_db_password:
    file: ./deploy/conf/postgres_password